import Product from '../../Models/Product';
import listFunction from '../../Helpers/list';
export const list = (req, res) =>  listFunction(Product, req, res, "Product", true);
import editFunction from '../../Helpers/edit';
export const edit = (req, res) =>  editFunction(Product, req, res, "Product", true);
import deleteFunction from '../../Helpers/delete';
export const remove = (req, res) =>  deleteFunction(Product, req, res, "Product", true);
import addFunction from '../../Helpers/add';
export const add = (req, res) => addFunction(Product, req, res, "Product", true);
import findByIdFunction from '../../Helpers/findById';
export const findById = (req, res) =>  findByIdFunction(Product, req, res, "Product", true);
import removeManyFunction from '../../Helpers/removeMany';
export const removeMany = (req, res) =>  removeManyFunction(Product, req, res, "Product", true);
import softlyRemoveFunction from '../../Helpers/softDelete';
export const softlyRemove = (req, res) =>  softlyRemoveFunction(Product, req, res, "Product", true);
import softlyRemoveManyFunction from '../../Helpers/softRemoveMany';
export const softlyRemoveMany = (req, res) =>  softlyRemoveManyFunction(Product, req, res, "Product", true);
import unpublishFunction from '../../Helpers/unpublish';
export const unpublish = (req, res) =>  unpublishFunction(Product, req, res, "Product", true);
import unpublishManyFunction from '../../Helpers/unpublishMany';
export const unpublishMany = (req, res) =>  unpublishManyFunction(Product, req, res, "Product", true);
import restoreManyFunction from '../../Helpers/restoreMany';
export const restoreMany = (req, res) =>  restoreManyFunction(Product, req, res, "Product", true);
import publishManyFunction from '../../Helpers/publishMany';
export const publishMany = (req, res) =>  publishManyFunction(Product, req, res, "Product", true);
