import Form from '../../Models/Form';
import listFunction from '../../Helpers/list';
export const list = (req, res) =>  listFunction(Form, req, res, "Form", true);
import editFunction from '../../Helpers/edit';
export const edit = (req, res) =>  editFunction(Form, req, res, "Form", true);
import deleteFunction from '../../Helpers/delete';
export const remove = (req, res) =>  deleteFunction(Form, req, res, "Form", true);
import addFunction from '../../Helpers/add';
export const add = (req, res) => addFunction(Form, req, res, "Form", true);
import findByIdFunction from '../../Helpers/findById';
export const findById = (req, res) =>  findByIdFunction(Form, req, res, "Form", true);
import removeManyFunction from '../../Helpers/removeMany';
export const removeMany = (req, res) =>  removeManyFunction(Form, req, res, "Form", true);
import softlyRemoveFunction from '../../Helpers/softDelete';
export const softlyRemove = (req, res) =>  softlyRemoveFunction(Form, req, res, "Form", true);
import softlyRemoveManyFunction from '../../Helpers/softRemoveMany';
export const softlyRemoveMany = (req, res) =>  softlyRemoveManyFunction(Form, req, res, "Form", true);
import unpublishFunction from '../../Helpers/unpublish';
export const unpublish = (req, res) =>  unpublishFunction(Form, req, res, "Form", true);
import unpublishManyFunction from '../../Helpers/unpublishMany';
export const unpublishMany = (req, res) =>  unpublishManyFunction(Form, req, res, "Form", true);
import restoreManyFunction from '../../Helpers/restoreMany';
export const restoreMany = (req, res) =>  restoreManyFunction(Form, req, res, "Form", true);
import publishManyFunction from '../../Helpers/publishMany';
export const publishMany = (req, res) =>  publishManyFunction(Form, req, res, "Form", true);
import findByTitleFunction from '../../Helpers/findByTitle';
export const findByTitle = (req, res) =>  findByTitleFunction(Form, req, res, "Form", true);
