import Project from '../../Models/Project';
import listFunction from '../../Helpers/list';
export const list = (req, res) =>  listFunction(Project, req, res, "Project", true);
import editFunction from '../../Helpers/edit';
export const edit = (req, res) =>  editFunction(Project, req, res, "Project", true);
import deleteFunction from '../../Helpers/delete';
export const remove = (req, res) =>  deleteFunction(Project, req, res, "Project", true);
import addFunction from '../../Helpers/add';
export const add = (req, res) =>  addFunction(Project, req, res, "Project", true);
import findByIdFunction from '../../Helpers/findById';
export const findById = (req, res) =>  findByIdFunction(Project, req, res, "Project", true);
import removeManyFunction from '../../Helpers/removeMany';
export const removeMany = (req, res) =>  removeManyFunction(Project, req, res, "Project", true);
import softlyRemoveFunction from '../../Helpers/softDelete';
export const softlyRemove = (req, res) =>  softlyRemoveFunction(Project, req, res, "Project", true);
import softlyRemoveManyFunction from '../../Helpers/softRemoveMany';
export const softlyRemoveMany = (req, res) =>  softlyRemoveManyFunction(Project, req, res, "Project", true);
import unpublishFunction from '../../Helpers/unpublish';
export const unpublish = (req, res) =>  unpublishFunction(Project, req, res, "Project", true);
import unpublishManyFunction from '../../Helpers/unpublishMany';
export const unpublishMany = (req, res) =>  unpublishManyFunction(Project, req, res, "Project", true);
