import User from '../../Models/User';
import listFunction from '../../Helpers/list';
export const list = (req, res) =>  listFunction(User, req, res, "User", true);
import editFunction from '../../Helpers/edit';
export const edit = (req, res) =>  editFunction(User, req, res, "User", true);
import deleteFunction from '../../Helpers/delete';
export const remove = (req, res) =>  deleteFunction(User, req, res, "User", true);
import addFunction from '../../Helpers/add';
export const add = (req, res) =>  addFunction(User, req, res, "User", true);
import findByIdFunction from '../../Helpers/findById';
export const findById = (req, res) =>  findByIdFunction(User, req, res, "User", true);
import removeManyFunction from '../../Helpers/removeMany';
export const removeMany = (req, res) =>  removeManyFunction(User, req, res, "User", true);
import softlyRemoveFunction from '../../Helpers/softDelete';
export const softlyRemove = (req, res) =>  softlyRemoveFunction(User, req, res, "User", true);
import softlyRemoveManyFunction from '../../Helpers/softRemoveMany';
export const softlyRemoveMany = (req, res) =>  softlyRemoveManyFunction(User, req, res, "User", true);
import unpublishFunction from '../../Helpers/unpublish';
export const unpublish = (req, res) =>  unpublishFunction(User, req, res, "User", true);
import unpublishManyFunction from '../../Helpers/unpublishMany';
export const unpublishMany = (req, res) =>  unpublishManyFunction(User, req, res, "User", true);
